### ISSUE TITLE
URL rewriting is not working

### ISSUE THREAD

**Issue by zhongh** [tetherless-world/dco-citations#1]
@zednis @mrpatrickwest Use DCO-ID "11121/3524-1246-5132-9229-CC" for our example.

`http://localhost/api.php?get_citation=11121/3524-1246-5132-9229-CC` will successfully return some information on the DCO-ID provided

I want to, by setting rewriting rules in `.htaccess` file, have a url rewriting such that 
`http://localhost/citation/11121/3524-1246-5132-9229-CC` will be rerouted to the original URL and yield the same result.

Currently I set in `.htaccess``  like this below, but nothing is working (URL Not Found).

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule ^citation/([a-zA-Z0-9/-]+)$ api.php?get_citation=$1
</IfModule>
```

**Comment by zednis** [comment]
Is there anything in the logs?

**Comment by zhongh** [comment]
@zednis There are two logs for apache in `/var/logs/apache2/`, one is `error_log` which shows nothing particular, the other log is `access_log` which shows

```
::1 - - [24/Mar/2016:20:59:26 -0400] "GET /api.php?action=get_citation&id=11121/3524-1246-5132-9229-CC HTTP/1.1" 200 180
::1 - - [24/Mar/2016:21:00:14 -0400] "GET /citation/11121/3524-1246-5132-9229-CC HTTP/1.1" 404 235
```

where the first record is a successful link and the second record shows page not found. Still couldn't figure out why the url rewriting is not working

**Comment by zhongh** [comment]
@zednis I believe that the problem is that the .htaccess is not working. Because I try to use the simplest rewriting rule and use link `/citation/abc`. It should lead to `/api.php?action=get_citation&id=abc` which should return an EMTPY result, but instead, it still shows URL not found. 

So obviously what I have set in `.htaccess` file is not working at all.

**Comment by zhonghao1014** [comment]
Just found something.. might work soon
