### ISSUE TITLE
Remove "Recommended Citation" Title in popover

### ISSUE THREAD

**Issue by mrpatrickwest** [tetherless-world/dco-citations#16]
According to engagement and secretariat the title is misleading. Their suggestion is to just remove it.

**Comment by zednis** [comment]
http://stackoverflow.com/questions/11224892/how-do-you-disable-the-title-in-twitter-bootstraps-popover-plugin

I am curious why they find the title misleading.

**Comment by mrpatrickwest** [comment]
Makes it sound like we're recommending they use a particular citation format when the citation format depends on the publication, journal, conference, etc...

**Comment by zednis** [comment]
Ah, ok.  I see there is a related issue at tetherless-world/dco-elasticsearch/issues/48; as there would be no change in this repository to implement this fix are you going to close this ticket or just close this ticket when the related ticket in dco-elasticsearch is closed?

**Comment by mrpatrickwest** [comment]
wasn't 100% sure that if I close the ticket that it'll still be referencable by the other repository ... but I don't see why it wouldn't so I think I'll close it.
