### ISSUE TITLE
make sure the dco-id represents a publication

### ISSUE THREAD

**Issue by mrpatrickwest** [tetherless-world/dco-citations#7]
Don't want to be trying to generate a citation for a foaf:Person, for example.

**Comment by zednis** [comment]
How about the service performs an initial query on the type of the resource associated with the DCO-ID and then determines which query to perform and citation to generate based on the type query results?

This would allow us to incrementally add citations for new types of publications that require different structure and would make it easy for the service to determine if the resource with the DCO-ID is inappropriate for generating a citation.

**Comment by zhongh** [comment]
Or, the initial query should be return more simpler information such as uri, resource type, etc. Then write different subsequent queries regarding different types of publications, so that we can incrementally make things work

I wrote that at some point before and it looks pretty neat too

**Comment by zhonghao1014** [comment]
Fixed by #11

**Comment by zhongh** [comment]
Fixed by #11
